using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace WebApiCoach.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class MotivationalMessageController : Controller
    {
        private static readonly string[] Messages = new[]
        {
            "“A arte de ser ora audacioso, ora prudente, é a arte de vencer.” – Napoleão Bonaparte",
            "“Nossos fracassos, às vezes, são mais frutíferos do que os êxitos.” – Henry Ford",
            "“Comemore os seus sucessos. Veja com humor os seus fracassos.” – Sam Walton",
            "“Não somos responsáveis apenas pelo que fazemos, mas também pelo que deixamos de fazer.” – Moliere",
            "“É costume de um tolo, quando erra, queixar-se dos outros. É costume de um sábio queixar-se de si mesmo.” – Sócrates",
            "“Existe o risco que você jamais pode correr. Existe o risco que você jamais pode deixar de correr.” – Peter Drucker",
            "“Mesmo que já tenhas feito uma longa caminhada, há sempre um novo caminho a fazer.” – Santo Agostinho",
            "“A felicidade não está em fazer o que a gente quer, e sim querer o que a gente faz.” – Jean Paul Sartre",
            "“É sempre divertido fazer o impossível.” – Walt Disney",
            "“Experiência é o nome que cada um dá a seus erros.” – Oscar Wilde",
            "“Somente os que ousam errar muito podem realizar muito.” – John F. Kennedy",
            "“Somos o que repetidamente fazemos. Portanto, a excelência não é um feito, é um hábito.” – Aristóteles",
            "“Toda empresa precisa ter gente que erra, que não tem medo de errar e que aprende com erro.” – Bill Gates",
            "“A confiança em si mesmo é o primeiro segredo do sucesso.” – Ralph Waldo Emerson",
            "“Aquele que pretende ser um líder tem que ser uma ponte.” – Provérbio Galês",
            "“Muda tuas ideias e mudarás teu mundo.” – Norman Vincent Peale",
            "“A vitória sempre foi de quem nunca duvidou dela.” – Raul Follerean",
            "“Se existe uma forma de fazer melhor, descubra-a.” – Thomas Edison",
            "“O problema é que a maioria das pessoas prefere um elogio que prejudique do que uma crítica que beneficie.” – Norman Vincent Peale",
            "“A sorte favorece a mente preparada.” – Louis Pasteur",
            "“Não há sucesso sem dificuldade.” – Sófocles",
            "“A maior recompensa pelo trabalho não é o que a pessoa ganha, é o que ela se torna através dele.” – John Ruskin",
            "“Não encontre defeitos, encontre soluções. Qualquer um sabe queixar-se.” – Henry Ford",
            "“Conhecimento não é aquilo que você sabe, mas o que você faz com aquilo que sabe.” – Aldous Huxley",
            "“Critica o que fazes, e não faças o que criticas.” – Provérbio Árabe",
            "“Se sonhar grande dá o mesmo trabalho que sonhar pequeno, por que vou sonhar pequeno?.” – Jorge Paulo Lemann",
            "“Por vezes sentimos que aquilo que fazemos não é senão uma gota de água no mar. Mas o mar seria menor se lhe faltasse uma gota.” – Madre Teresa de Calcutá",
            "“Destino não é exterior a nós; somos nós que criamos nosso próprio destino dia após dia.” – Henry Miller",
            "“Ontem foi ontem, já passou. Hoje é hoje e é o que nos importa. Amanhã, o futuro, a Deus pertence.” – Samuel Klein",
            "“Você precisa fazer aquilo que pensa que não é capaz de fazer.” – Eleanor Roosevelt",
            "“Faça o que puder, com o que tiver, onde estiver.” – Theodore Roosevelt",
            "“A vida é curta demais. Não corra o risco de passar seus dias apenas afinando seu instrumento sem jamais fazer um grande espetáculo.” – Carlos Wizard Martins",
            "“Tudo que você precisa fazer é mover as pessoas só um pouquinho para mudanças acontecerem. Não precisa ser algo enorme.” – Viola Davis",
            "“Nossas dúvidas são traidoras e nos fazem perder, por medo de tentar, o que poderíamos ganhar.” – William Shakespeare",
            "“Se você quer fazer uma coisa realmente grande, seja grande como a coisa que você quer fazer.” – Nizan Guanaes",
            "“Aquele que é feliz, espalha felicidade. Aquele que teima na infelicidade, que perde o equilíbrio e a confiança, perde-se na vida.” – Anne Frank",
            "“Os problemas são apenas oportunidades com roupas de trabalho.” – Henry John Kaiser",
            "“Na crise, existem aqueles que se abatem, sentam no chão e choram; e existem aqueles que fabricam e vendem lenços. Nós somos fabricantes de lenços.” – Abilio Diniz",
            "“Levanto a minha voz, não para que eu possa gritar, mas para que aqueles sem voz possam ser ouvidos….” – Malala Yousafzai",
            "“Em todas as situações, deve-se considerar o objetivo.” – Jean de La Fontaine",
            "“Se você quer saber o quanto você é forte, é na necessidade que descobrimos que somos gigantes.” – Cleusa Maria da Silva",
            "“Só se aprende com a experiência. Portanto, não importa o que as pessoas lhe digam, você tem que viver e cometer seus próprios erros para aprender.” – Emma Watson",
            "“É o motivo que engrandece a ação; é o fazer, não o feito.” – Margaret Preston",
            "“Um grande líder é exemplo pela atitude, não pelo discurso.” – Robinson Shiba",
            "“Sucesso é mais frequentemente alcançado por aqueles que não sabem que o fracasso é inevitável.” – Coco Chanel",
            "“Quem vive sem disciplina morre sem honra.” – Provérbio islandês",
            "“Um dia é preciso parar de sonhar, tirar os planos da gaveta e, de algum modo, começar.” – Amyr Klink",
            "“A maior descoberta de todos os tempos é que uma pessoa pode mudar, simplesmente mudando de atitude.” – Oprah Winfrey",
            "“Mesmo se você estiver no caminho certo será atropelado se ficar sentado nele.” – Will Rogers",
            "“O fundamental é manter sempre a mesma obsessão em alcançar o sucesso. Ter sucesso não é apenas ter dinheiro, mas sim saber que uma ideia que parece impossível pode vir a ser uma empresa que irá quebrar paradigmas.” – Romero Rodrigues",
            "“O jeito mais eficiente de fazer algo é fazendo.” – Amelia Earhart",
            "“O insucesso é uma oportunidade para recomeçar com mais inteligência.” – Henry Ford",
            "“O liderado será reflexo da sua liderança, então quem espera lealdade, primeiro deve ser leal.” – Flávio Augusto",
            "“Sozinhos, pouco podemos fazer; juntos, podemos fazer muito.” – Helen Keller",
            "“Uma atitude vitoriosa é meio caminho andado para o sucesso.” – Arthur Riedel",
            "“Quando diz ‘estou cada vez melhor’, você erotiza, ilumina com amor, um olhar, um pensamento, e suas circunstâncias. Você vence a sombra. Assim, convocando a beleza, vence a tendência à banalização da vida, que por vezes predomina à nossa volta.” – Antônio Luiz Seabra",
            "“Lembre-se que não conseguir o que você quer é algumas vezes um lance de sorte.” – Dalai Lama",
            "“E o problema é que, se você não arrisca nada, você arrisca mais.” – Erica Jong",
            "“Nada é mais desafiador do que superar uma situação não planejada.” – Nelson Sirotsky",
            "“Perde tudo quem perde o momento certo.” – Provérbio espanhol",
            "“A fórmula da felicidade e do sucesso é simplesmente ser você mesmo da maneira mais sincera que puder.” – Meryl Streep",
            "“Eu não tenho Ídolos. Tenho admiração por trabalho, dedicação e competência.” – Ayrton Senna",
            "“Você nunca pode atravessar o oceano até que você tenha coragem de perder de vista a costa.” – Cristóvão Colombo",
            "“O segredo do nosso sucesso é que nós nunca, nunca desistimos.” – Wilma Mankiller",
            "“ Não importa o quão rápido você anda, mas a força de vontade para nunca parar.” – Confúcio",
            "“Não perca tempo tentando mudar a opinião dos outros. Faça seu trabalho e não ligue para o que pensam.” – Tina Fey",
            "“ Você não pode deixar de usar a criatividade. Quanto mais você usa, mais você tem.” – Maya Angelou",
            "“Há apenas uma maneira de evitar críticas: não fazer, não falar e não ser nada .” Aristóteles",
            "“Sonhos são adoráveis. Mas são só sonhos. São fugazes, efêmeros, bonitos. Sonhos não se tornarão realidade só porque você sonhou. É o esforço que faz as coisas acontecerem. É o esforço que cria mudança.” – Shonda Rhimes",
            "“Ter problemas na vida é inevitável. Ser derrotado por eles é opcional.” – Roger Crowford",
            "“Seu tempo é limitado, então não perca tempo vivendo a vida de outra pessoa.” – Steve Jobs",
            "“Mude a sua vida hoje. Não deixe para arriscar no futuro, aja agora, sem atrasos.” – Simone de Beauvoir",
            "“É importante aprender a não se aborrecer com opiniões diferentes das suas.” – Bertrand Russell",
            "“Na adversidade, uns desistem, enquanto outros batem recordes.” – Ayrton Senna",
            "“Espíritos grandiosos sempre encontraram oposição violenta de mentes medíocres.” – Albert Einstein",
            "“Quando você tropeçar, mantenha a fé. Quando for nocauteado, levante rápido. Não ouça quem diz que você não pode ou não deve continuar.” – Hillary Clinton",
            "“A distância entre o sonho e a realidade, chama-se disciplina.” – Bernardinho",
            "“Mestre não é quem sempre ensina, mas quem de repente aprende.” – João Guimarães Rosa",
            "“Se fizemos um planejamento e estabelecemos metas, o resultado tem de aparecer. Eu não gosto de bengalas, que é como eu chamo quando a pessoa chega e vai apresentando uma desculpa. Traga o problema e também uma solução.” – Sonia Hess",
            "“O mundo está na mão daqueles que têm a coragem de sonhar e de correr o risco de viver seus sonhos.” – Paulo Coelho",
            "“Tenho aprendido ao longo dos anos que, quando a mente está pronta, isso diminui o medo.” – Rosa Parks",
            "“Você falha, e aí? A vida continua. É só quando você se arrisca a falhar que descobre coisas.” – Lupita Nyong’o",
            "“No fim tudo dá certo, e se não deu certo é porque ainda não chegou ao fim.” – Fernando Sabino",
            "“O mais corajoso dos atos ainda é pensar com a própria cabeça.” – Coco Chanel",
            "“Alguns fracassos são inevitáveis. É impossível viver sem fracassar em alguma coisa, a não ser que você viva tomando tanto cuidado com tudo que você simplesmente não viva.” – J. K. Rowling",
            "“As invenções são o resultado de um trabalho teimoso.” – Santos Dumont",
            "“Nada contribui tanto para clarear a mente do que um objetivo claro.” – Marry W. Shelley",
            "“Às vezes a gente tem de ser meio louco mesmo, extremamente obstinado, porque a loucura funciona – desde que exista disciplina, um objetivo muito claro, pé no chão e a humildade de saber que a gente vai errar muito, vai aprender com os erros e continuar.” – Leila Velez",
            "“Não existe falta de tempo, existe falta de interesse. Porque quando a gente quer mesmo, a madrugada vira dia. Quarta-feira vira sábado e um momento vira oportunidade.” – Pedro Bial",
            "“Tudo o que você sempre quis está do outro lado do seu medo.” – George Addair",
            "“Você não crescerá a não ser que tente algo além daquilo que já domina.” – Ronald Osborn",
            "“Faça coisas. Seja curioso, persistente. Não espere por um empurrão da inspiração ou por um beijo da sociedade na sua testa. Preste atenção. É tudo sobre prestar atenção. É tudo sobre captar o máximo que você puder do que está por aí e não deixar que desculpas e que a monotonia de algumas obrigações diminuam sua vida.” – Susan Sontag",
            "“Você pode mudar sem crescer, mas não pode crescer sem mudar.” – Larry Wilson",
            "“Quanto mais velha eu fico, mais me interesso pelas mulheres. Ainda não conheci uma mulher que não é forte. Elas não existem.” – Diane von Furstenberg",
            "“Nossa paciência conquistará mais do que a nossa força.” – Edmund Burke",
            "“Respeite sua essência, seja você mesma, é o jeito mais inteligente de construir seu estilo, sua maneira de viver e de se vestir. E você vai ver: estilo é fundamental para a autoestima.” – Constanza Pascolato",
            "“Certifique-se de que suas palavras e seus atos estão em harmonia.” – Claus Moller",
            "“Descubra quem você é e seja essa pessoa. Isso é o que sua alma foi colocada nesta Terra para ser. Encontre essa verdade, viva essa verdade e tudo mais virá.” – Ellen Degeneres",
            "“Quanto maior a dificuldade maior é o mérito de superá-la.” – H. W. Beecher",            
            "“Não há saber mais ou saber menos: há saberes diferentes.” – Paulo Freire",
            "“Nunca é tarde demais para ser o que você poderia ter sido.” – George Eliot",
            "“Ao fim do dia, podemos aguentar muito mais do que pensamos que podemos.” – Frida Kahlo",
            "“Ouça qualquer um que tenha uma ideia original. Encoraje-o. Deixe as pessoas continuarem suas ideias.” – William McKnight",
            "“Esforce-se para não ser um sucesso, mas sim para ser valioso.”. Albert Einstein",
            "“Eu defino o poder pela confiança para tomar suas próprias decisões, para não ser influenciado por outras pessoas, e ser corajoso e destemido ao saber que, mesmo se você tomar a decisão errada, você fez isso por uma boa razão.” – Adele",
            "“Não ergas um edifício sem fortes alicerces ou viverás com medo.” – Sabedoria Persa",
            "“Você está aqui por uma razão, muitas vezes suas inseguranças e sua falta de experiência podem te levar a se apegar às expectativas ou valores de outras pessoas. Você pode aproveitar isso para esculpir seu caminho, livre da carga de saber como as coisas devem ser, definido por suas particularidades.” – Natalie Portman",
            "“Você nunca vai chegar ao seu destino se você parar e atirar pedras em cada cão que late.” – Winston Churchill",
            "“Assistir a grandes pessoas fazerem o que você ama é uma boa maneira de se inspirar.” – Amy Poehler",
            "“Uma pessoa que nunca cometeu um erro, nunca tentou nada de novo.”. Albert Einstein",
            "“Eu não sonhei com sucesso. Eu trabalhei para ele.” – Estée Lauder",
            "“Ganhar não é tudo, mas querer ganhar é.” – Vince Lombardi",
            "“Os meus maiores sucessos chegaram no seguimento de grandes fracassos.” – Barbara Corcoran",
            "“Sonhe grande e se atreva a falhar.” – Norman Vaughan",
            "“Não espere por grandes líderes; faça você mesmo, pessoa a pessoa. Seja leal às ações pequenas porque é nelas que está a sua força.” – Madre Teresa de Calcutá",
            "“Você pode ficar desapontado se falhar, mas já está derrotado se não tentar.”. Beverly Sills",
            "“Aprendi a aceitar desafios que nunca pensei fazer antes. Sucesso e conforto não podem coexistir.” – Ginni Rometty",
            "“Na vida sempre fazemos escolhas. Ainda que escolhemos não escolher.”. Carmen Miranda",
            "“Sempre fiz algo que eu achava que estava pouco preparada para fazer. Quando você tem um momento de incerteza mas persiste, é aí que você consegue avançar.” – Marissa Mayer",
            "“Quem sabe faz a hora, não espera acontecer.” – Geraldo Vandré",
            "“Defina sucesso com seus próprios termos, o alcance segundo as suas próprias regras e viva uma vida da qual você se orgulhe.” – Anne Sweeney",
            "“O sucesso nasce do querer, da determinação e persistência em se chegar a um objetivo. Mesmo não atingindo o alvo, quem busca e vence obstáculos, no mínimo fará coisas admiráveis” – José de Alencar",
            "“Se você quer ser bem-sucedido precisa de dedicação total, buscar seu último limite e dar o melhor de si mesmo” – Ayrton Senna",
            "“Não crie limites para si mesmo. Você deve ir tão longe quanto sua mente permitir. O que você mais quer pode ser conquistado” – Mary Kay Ash",
            "“Nenhum obstáculo será grande se a sua vontade de vencer for maior” – Autor desconhecido",
            "“Dificuldades preparam pessoas comuns para destinos extraordinários” C.S Lewis",
            "“Nenhum homem será um grande líder se quiser fazer tudo sozinho ou se quiser levar todo o crédito por fazer isso” – Andrew Carnegie",
            "“Bom mesmo é ir à luta com determinação, abraçar a vida com paixão, perder com classe e vencer com ousadia, porque o mundo pertence a quem se atreve e a vida é muito curta, para ser insignificante” — Charlie Chaplin",
            "“Pessoas vencedoras não são aquelas que não falham, são aquelas que não desistem”  – Autor desconhecido",
            "“Só existem dois dias do ano em que você não pode fazer nada: um se chama ontem e outro amanhã” – Dalai Lama",
            "“A vida é um constante recomeço. Não se dê por derrotado e siga adiante. As pedras que hoje atrapalham sua caminhada amanhã enfeitarão a sua estrada”  – Autor desconhecido",
            "“Ouse ir além, ouse fazer diferente e o poder lhe será dado!” – José Roberto Marques",
            "“Ouse, arrisque, não desista jamais e saiba valorizar quem te ama, esses sim merecem seu respeito. Quanto ao resto, bom, ninguém nunca precisou de restos para ser feliz” – Clarice Lispector",
            "“Para ser um campeão você tem que acreditar em si mesmo quando ninguém mais acredita” – Muhammad Ali",
            "“No fim tudo dá certo, e se não deu certo é porque ainda não chegou ao fim” – Fernando Sabino",
            "“Você nunca sabe que resultados virão da sua ação. Mas se você não fizer nada, não existirão resultados” – Mahatma Gandhi",
            "“O pessimista vê dificuldade em toda oportunidade. O otimista vê oportunidade em toda dificuldade” – Winston Churchill",
            "“A paciência é um elemento fundamental do sucesso” – Bill Gates",
            "“Reclamar não é uma estratégia. É necessário lidarmos com o mundo como ele é e não como gostaríamos que ele fosse” – Jeff Bezos. ",
            "“O sucesso não tem a ver com o lugar de onde você veio, e sim com a confiança que você tem e o esforço que você está disposto a investir” – Michelle Obama",
            "“Você pode encarar um erro como uma besteira a ser esquecida, ou como um resultado que aponta uma nova direção” – Steve Jobs",
            "“Você não pode ser uma pessoa difícil, tímida, que não é capaz de olhar alguém nos olhos; você tem que se apresentar. Você tem que saber como falar sobre si mesmo, sua visão, o seu foco e em que você acredita” – Anna Wintour",
            "“Eu posso aceitar a falha, todos falham em alguma coisa. Mas eu não posso aceitar não tentar” – Michael Jordan",
            "“Gostaria que você soubesse que existe dentro de si uma força capaz de mudar sua vida. Basta que lute e aguarde um novo amanhecer” – Margaret Thatcher",
            "“Inteligência é a capacidade de se adaptar às mudanças” – Stephen Hawking",
            "“Quanto mais eu me conheço, mais eu me curo e me potencializo.”- José Roberto Marques",
            "“Se não gosta de alguma coisa, mude-a. Se não puder mudá-la, mude a sua atitude. Não reclame.” – Maya Angelou",
            "“O que não provoca minha morte faz com que eu fique mais forte.” – Friedrich Nietzsche",
            "“Se você quiser alguém em quem confiar, confie em si mesmo, quem acredita sempre alcança”- Renato Russo",
            "“Muitas vezes perdemos a possibilidade de felicidade de tanto nos prepararmos para recebê-la. Por que então não agarrá-la toda de uma vez?” – Jane Austen",
            "“Os professores abrem a porta, mas você deve entrar por você mesmo.” – provérbio chinês",
            "“No fundo sabemos que o outro lado de todo o medo é a liberdade.” – Marilyn Ferguson",
            "“O sucesso não tem a ver com o lugar de onde você veio, e sim com a confiança que você tem e o esforço que você está disponível a investir” – Michelle Obama",
            "“Imagine uma nova história para sua vida e acredite nela.” – Paulo Coelho",
            "“O sucesso nasce do querer, da determinação e persistência em se chegar a um objetivo. Mesmo não atingindo o alvo, quem busca e vence obstáculos, no mínimo fará coisas admiráveis.” – José de Alencar",
            "“Para ter um negócio de sucesso, alguém, algum dia, teve que tomar uma atitude de coragem.” – Peter Drucker",
            "“Para sempre é composto de agoras.”- Emily Dickinson",
            "“Que ninguém se engane, só se consegue a simplicidade através de muito trabalho.” – Clarice Lispector",
            "“Tentar e falhar é, pelo menos, aprender. Não chegar a tentar é sofrer a inestimável perda do que poderia ter sido.” – Albino Teixeira",
            "“A tentação de desistir será um pouco maior antes de você estar prestes a conseguir.” –  Provérbio Chinês",
            "“As pessoas dizem frequentemente que a motivação não dura. Bem, nem o banho e é por isso que ele é recomendado diariamente.” – Zig Ziglar",
            "“O insucesso é apenas uma oportunidade para recomeçar de novo com mais inteligência.”  – Henry Ford",
            "“Se você pensa que consegue fazer algo ou pensa que não consegue fazer algo, você está certo.” – Henry Ford",
            "“A grandeza não consiste em receber honras, mas em merecê-las.” – Aristóteles",
            "“A persistência é o caminho do êxito.” – Charles Chaplin",
            "“Acredite em milagres, mas não dependa deles.” – Immanuel Kant",
            "“Não espere por circunstâncias ideais. Elas nunca chegam.” – Janet Stuart",
            "“Há apenas uma maneira de evitar críticas: não fazer, não falar e não ser nada.” – Aristóteles",
            "“A vida é como andar de bicicleta. Para conseguir o equilíbrio, você precisa se manter em movimento.” – Albert Einstein",
            "“Você pode conseguir qualquer coisa que queira na vida, se você ajudar outras pessoas a conseguirem o que elas querem.” Zig Ziglar",
            "“Insanidade é continuar fazendo sempre a mesma coisa e esperar resultados diferentes.” – Albert Einstein",
            "“Podemos facilmente perdoar uma criança que tem medo do escuro; a real tragédia da vida é quando os homens têm medo da luz.” – Platão",
            "“O sábio nunca diz tudo o que pensa, mas pensa sempre tudo o que diz.” – Aristóteles",
            "“Viva de modo que tuas atitudes falem tão alto que não seja necessário que tu digas palavra alguma!” – Augusto Branco",
            "“Dizem que a vida é para quem sabe viver, mas ninguém nasce pronto. A vida é para quem é corajoso o suficiente para se arriscar e humilde o bastante para aprender.” – Clarice Lispector",
            "“Até as torres mais altas começaram do chão.” – Provérbio Chinês",
            "“Transformar ideias em projetos e estes em ações é para pessoas empreendedoras. Se não o fizer, alguém o fará e você passará a ser um mero expectador do sucesso.” – Roberto Rabello",
            "“Para o verdadeiro sucesso, pergunte a si mesmo 4 questões: Por que? Por que não? Por que não eu? Por que não agora?” – James Allen",
            "“Os dias prósperos não vêm por acaso. Nascem de muito trabalho e persistência” – Henry Ford",
            "“Nenhum trabalho de qualidade pode ser feito sem concentração e auto-sacrifício, esforço e dúvida.” – Max Beerbohm",
            "“O gênio é um por cento de inspiração e noventa e nove por cento de suor.” – Thomas Edison",
            "“Lembre-se: o sucesso é uma jornada, não um destino. Tenha fé em sua capacidade.”  – Bruce Lee",
            "“A educação tem raízes amargas, mas os seus frutos são doces.” – Aristóteles",
            "“A alegria que se tem em pensar e aprender faz-nos pensar e aprender ainda mais.” – Aristóteles",
            "“Há três métodos para ganhar sabedoria: primeiro, por reflexão, que é o mais nobre; segundo, por imitação, que é o mais fácil; e terceiro, por experiência, que é o mais amargo.” – Confúcio",
            "“A qualidade mais valiosa para o aprendizado é uma atitude positiva.” – Bobbi DePorter",
            "“Mudar é difícil mas é possível.” – Paulo Freire",
            "“O segredo do bem-estar não é eliminar as emoções negativas, mas ser capaz de gerí-las quando elas ocorrem.” – Flora Victoria",
            "“Para sentir o amor, devemos antes comunicar o amor em atos, palavras e ações.”  Paulo Vieira",
            "“Ocupe-se vivendo ou ocupe-se morrendo” - Stephen King",
            "“Sonhe como se você fosse viver para sempre, viva como se fosse morrer hoje” - James Dean",
            "“Não deixe o que você não pode fazer interferir no que pode” - John R. Wooden",
            "“Não é para o que você olha que importa, é o que você vê” - Henry David Thoreau",
            "“Não julgue cada dia pelo quanto você colhe, mas pelas sementes que planta” - Robert Louis Stevenson",
            "“Todo momento é um novo começo” - T.S. Eliot",
            "“O tipo de liberdade mais importante é ser quem você é” - Jim Morrison",
            "“A hora é sempre certa para fazer a coisa certa” - Martin Luther King",
            "“Se você não gosta da estrada que está percorrendo, comece a construir outras” - Dolly Parton",
            "“A função da liderança é criar mais líderes, não mais seguidores” - Ralph Nader",
            "“A inspiração costuma surgir durante o trabalho, e não antes dele” - Madeleine L’Engle",
            "“Um dia de impacto é melhor que um mês de peso morto” - Oliver Wendell Holmes",
            "“O sucesso não é um acidente. É trabalho duro, perseverança, aprendizagem, estudo e sacrifício” - Pelé",
            "“Ninguém que deu seu melhor se arrependeu” - George Halas",
            "“Não é a vontade de vencer que importa — todo mundo a tem. É a vontade de se preparar para vencer que conta” - Bear Bryant",
            "“Você tem que acreditar em si mesma quando ninguém mais acredita — só isso já faz de você uma vencedora” - Venus Williams",
            "“A dor é temporária. Ela pode durar um minuto, uma hora, um dia ou um ano, mas eventualmente ela vai diminuir e algo vai substituí-la. Desistir, entretanto, dura para sempre” - Lance Armstrong",
            "“Não se venda. Você é tudo o que tem” - Janis Joplin",
            "“Se você não está cometendo erros, não está tomando decisões” - Catherine Cook",
            "“A forma mais comum com que as pessoas desistem do seu poder é pensando que não têm nenhum” - Alice Walker",
            "“Se você quer que os outros sejam felizes, pratique compaixão. Se você quer ser feliz, pratique compaixão” - Dalai Lama",
            "“Não é o que você tem, quem é, onde está ou o que está fazendo que o fazem feliz ou infeliz. É o que você pensa sobre tudo isso” - Dale Carnegie",
            "“A mente é seu próprio espaço, e ela própria pode fazer do inferno um paraíso; e do paraíso, um inferno” - John Milton",
            "“A arte de viver está menos em eliminar problemas e mais em crescer com eles” - Bernard M. Baruch",
            "“Se você quer ser feliz, estabeleça um objetivo que comande seus pensamentos, libere sua energia e inspire suas esperanças” - Andrew Carnegie",
            "“Você tem que experimentar tristeza para conhecer felicidade, e eu lembro a mim mesma que nem todo dia será bom e que as coisas são assim!” - Dita Von Teese",
            "“A única coisa que vai fazer você feliz é ser feliz com quem você é, e não com quem as pessoas acham que você é” - Goldie Hawn",
            "“Não se pode viajar até felicidade, possuí-la, ganhá-la, desgastá-la ou consumi-la. A felicidade é a experiência espiritual de viver cada minuto com amor, graça e gratidão” - Denis Waitley",
            "“Sucesso é a soma de pequenos esforços, dia a dia” - Robert Collier",
            "“Sucesso é gostar de si mesmo, do que você faz e como faz” - Maya Angelou",
            "“A maior parte das coisas importantes no mundo foi alcançada por pessoas que continuaram tentando mesmo não tendo nenhuma ajuda” - Dale Carnegie",
            "“O fracasso é um sucesso, se aprendermos com ele” - Malcolm Forbes",
            "“Nunca é cedo demais para ser gentil, porque você nunca sabe o quão cedo é tarde demais” - Ralph Waldo Emerson",
            "“Ganhar uma guerra é tão desastroso quanto perdê-la.” – Agatha Christie",
            "“Cultive todas as pessoas, as certas vão brotar.” – Aluísio de Paula",
            "“Não viva para que sua presença seja notada, mas para que sua falta seja sentida.” – Bob Marley",
            "“O que somos é consequência do que pensamos.” – Buda",
            "“Na vida sempre fazemos escolhas. Ainda que escolhemos não escolher.” – Carmen Miranda",
            "“Até cortar os próprios defeitos pode ser perigoso. Nunca se sabe qual é o defeito que sustenta nosso edifício inteiro.” – Clarice Lispector",
            "“Feliz aquele que transfere o que sabe e aprende o que ensina.” – Cora Coralina",
            "“Todos estamos matriculados na escola da vida, onde o mestre é o tempo.” – Cora Coralina",
            "“Sente-se sufocado aquele sem um objetivo de vida.” – Fiódor Dostoiévski",
            "“A única coisa que sabemos sobre o futuro é que ele será diferente.” – Peter Drucker",
            "“A mente é como um pára-quedas: só funciona aberta.” – Frank Zappa",
            "“Seja a mudança que você quer ver no mundo.” – Mahatma Gandhi",
            "“Todo mundo tem talento, é só uma questão de se mexer até descobrir qual é.” – George Lucas",
            "“Não abandone suas três grandes e inabaláveis amigas: a intuição, a inocência e a fé.” – George Gurdjieff",
            "“As pessoas que espalham amor não têm tempo nem disposição para jogar pedras.” – Irmã Dulce",
            "“É preciso ter dúvidas. Só os estúpidos têm uma confiança absoluta em si mesmos.” – Orson Welles",
            "“A amizade é um amor que nunca morre.” – Mario Quintana",
            "“Coragem é a resistência ao medo e não à ausência dele.” – Mark Twain",
            "“Para cada noite escura, há um dia brilhante.” – Tupac Shakur",
            "“Uma jornada de mil milhas começa com um simples passo.” – Lao Tzu",

        };

        private readonly ILogger<MotivationalMessageController> _logger;

        public MotivationalMessageController(ILogger<MotivationalMessageController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public IEnumerable<MotivationalMessage> Get()
        {
            var rng = new Random();
            return Enumerable.Range(1, 1).Select(index => new MotivationalMessage
            {
                Message = Messages[rng.Next(Messages.Length)]
            })
            .ToArray();
        }
    }
}
